### ISSUE TITLE
academia遇到些问题

### ISSUE THREAD

**Issue by miaorg0524** [PhosphorW/hexo-theme-academia#1]
您好！我在下载academia并更换主题后遇到些问题，向您请教一下！
在更换主题且应用后(hexo d)网页界面只显示一行字
extends includes/layout block content .page(itemscope itemtype='http://schema.org/CreativeWork') each article in page.posts.data if article.academia article!= article.content
请问您知道如何解决吗？拜托了！感谢！

**Comment by PhosphorW** [comment]
你需要安装两个renderer：
`npm install hexo-renderer-pug hexo-renderer-stylus --save`

**Comment by miaorg0524** [comment]
谢谢！

苗润丰
Runfeng(Franklin) Miao
重庆大学―辛辛那提大学联合学院
Chongqing University-University of Cincinnati
Joint Co-op Institute
2017级电气工程专业
Electrical Engineering
Class of 2022

________________________________
发件人: Phower <notifications@github.com>
发送时间: Thursday, April 2, 2020 8:28:06 PM
收件人: PhosphorW/hexo-theme-academia <hexo-theme-academia@noreply.github.com>
抄送: Miao, Runfeng (miaorg) <miaorg@mail.uc.edu>; Author <author@noreply.github.com>
主题: Re: [PhosphorW/hexo-theme-academia] academia遇到些问题 (#1)


你需要安装两个renderer：
npm install hexo-renderer-pug hexo-renderer-stylus --save

―
